// packages/example/src/components/Container.tsx
import { ObservablePoint, Texture } from "pixi.js";
import { For } from "solid-js";
import {
  Application,
  Container,
  ContainerProps,
  Sprite,
  useApp,
} from "solid-pixi";

const texture = Texture.from("/bunny.png");
texture.defaultAnchor = { x: 0.5, y: 0.5 } as ObservablePoint;

export default function ContainerPage() {
  return (
    <Application background="#1099bb">
      <RotatingHalvedContainer>
        <For each={Array.from({ length: 25 })}>
          {(_, i) => (
            <Sprite
              from={texture}
              x={(i() % 5) * 40}
              y={Math.floor(i() / 5) * 40}
            />
          )}
        </For>
      </RotatingHalvedContainer>
    </Application>
  );
}

function RotatingHalvedContainer(props: ContainerProps) {
  const app = useApp();

  return (
    <Container
      {...props}
      use={(container) => {
        const update = (delta: number) => {
          container.rotation -= 0.01 * delta;
        };
        app?.ticker.add(update);

        // unfortunately not all children's properties have been set by the time the use exists
        setTimeout(() => {
          container.pivot.set(container.width / 2, container.height / 2);
        });
        return () => app?.ticker.remove(update);
      }}
      x={(app?.screen?.width || 0) / 2}
      y={(app?.screen?.height || 0) / 2}
    >
      {props.children}
    </Container>
  );
}

// packages/docs/src/components/Container/Container.tsx
import { type PointLike, Ticker } from 'pixi.js'
import { Application, For, Loading, P, Stage, render, useApplication, useAsset } from 'solid-pixi'

render(() => <ContainerExample canvas={document.getElementById('root')! as HTMLCanvasElement} />)

function ContainerExample(props) {
  return (
    <Application background="#1099bb" resizeTo={window} canvas={props.canvas}>
      <Stage>
        <BunniesContainer />
      </Stage>
    </Application>
  )
}

function BunniesContainer() {
  const app = useApplication()
  const resource = useAsset('https://pixijs.com/assets/bunny.png')

  return (
    <Loading>
      <P.Container
        x={app.screen.width / 2}
        y={app.screen.height / 2}
        ref={container => {
          container.pivot = { x: 100, y: 100 }
          const handler = (delta: Ticker) => {
            // rotate the container!
            // use delta to create frame-independent transform
            container.rotation -= 0.001 * delta.deltaMS
          }
          app.ticker.add(handler)

          return () => {
            app.ticker.remove(handler)
          }
        }}
      >
        <For each={Array.from({ length: 25 })} fallback={<></>}>
          {(_, i) => (
            <P.Sprite
              texture={resource()}
              anchor={{ x: 0.5, y: 0.5 } as PointLike}
              x={(i() % 5) * 40}
              y={Math.floor(i() / 5) * 40}
            />
          )}
        </For>
      </P.Container>
    </Loading>
  )
}
